### ISSUE TITLE
Docker container crashing right away

### ISSUE THREAD

**Issue by mrzool** [IBM/aspera-cli#97]
The container based on [martinlaurent/ascli](https://hub.docker.com/r/martinlaurent/ascli) crashes right after being started giving this error:

```
W, [2022-12-04T09:55:08.965736 #1]  WARN -- : No config file found. Creating empty configuration file: /home/cliuser/.aspera/ascli/config.yaml
W, [2022-12-04T09:55:08.966031 #1]  WARN -- : Saving automatic conversion.
/usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:490:in `rescue in read_config_file': Permission denied @ rb_sysopen - /home/cliuser/.aspera/ascli/config.yaml (Aspera::Cli::CliError)
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:409:in `read_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:106:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `<top (required)>'
	from /usr/local/bundle/bin/ascli:25:in `load'
	from /usr/local/bundle/bin/ascli:25:in `<main>'
/usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:1030:in `write': Permission denied @ rb_sysopen - /home/cliuser/.aspera/ascli/config.yaml (Errno::EACCES)
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:1030:in `save_presets_to_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:471:in `read_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:106:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `<top (required)>'
	from /usr/local/bundle/bin/ascli:25:in `load'
	from /usr/local/bundle/bin/ascli:25:in `<main>'

```

**Comment by laurent-martin** [comment]
Hi,

The error here tells that ascli cannot create the config file: /home/cliuser/.aspera/ascli/config.yaml
due toi access rights.
How do you start the container ? just `docker run` ?
typically, you can mount a writable voume to keep persistency of the config file, examplke of start script:
/home/cliuser/.aspera/ascli/config.yaml
Anyway, it should not crash right away, I'll give it a look (and do a new release, as there was a new release of ascli as well)

**Comment by mrzool** [comment]
Thanks for the very quick reply. I tried both starting manually as per instructions [here](https://hub.docker.com/r/martinlaurent/ascli) with:

```
$ docker pull martinlaurent/ascli:latest
$ mkdir -p $HOME/.aspera/ascli
$ docker run --tty --interactive --rm \
--env ASCLI_HOME=/usr/src/app/config \
--volume $HOME/.aspera/ascli:/usr/src/app/config \
martinlaurent/ascli:latest ascli
```

and via helper script (`dascli`). Got the same error on both attempts.

How should I change the above command to fix this?

Thanks!

**Comment by laurent-martin** [comment]
Oh, I see,

in fact in the latest version, the container config folder is: /home/cliuser/.aspera/ascli
not anymore: /usr/src/app/config

The container page needs to be updated.

**Comment by mrzool** [comment]
> The container page needs to be updated.

The helper script too, apparently :) I'll give it another try later.

🙏

**Comment by mrzool** [comment]
The command `docker run --tty --interactive --rm --env ASCLI_HOME=/home/cliuser/.aspera/ascli --volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli martinlaurent/ascli:latest ascli` is still failing with a permission error on my machine:

```
W, [2022-12-04T14:57:21.658270 #1]  WARN -- : No config file found. Creating empty configuration file: /home/cliuser/.aspera/ascli/config.yaml
W, [2022-12-04T14:57:21.658571 #1]  WARN -- : Saving automatic conversion.
/usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:490:in `rescue in read_config_file': Permission denied @ rb_sysopen - /home/cliuser/.aspera/ascli/config.yaml (Aspera::Cli::CliError)
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:409:in `read_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:106:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `<top (required)>'
	from /usr/local/bundle/bin/ascli:25:in `load'
	from /usr/local/bundle/bin/ascli:25:in `<main>'
/usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:1030:in `write': Permission denied @ rb_sysopen - /home/cliuser/.aspera/ascli/config.yaml (Errno::EACCES)
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:1030:in `save_presets_to_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:471:in `read_config_file'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/plugins/config.rb:106:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/lib/aspera/cli/main.rb:137:in `initialize'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `new'
	from /usr/local/bundle/gems/aspera-cli-4.10.0/bin/ascli:29:in `<top (required)>'
	from /usr/local/bundle/bin/ascli:25:in `load'
	from /usr/local/bundle/bin/ascli:25:in `<main>'
```

**Comment by laurent-martin** [comment]
I see,

The issue is the following:
ascli docker image v4.10.0 is built to run as `cliuser` with uid 1000 (in container)

when running the container with volume, the volume belongs to root (in container) and the `cliuser` does not have write access.

One workaround is to add the following arguments: `--user root --env ASCLI_HOME=/home/cliuser/.aspera/ascli`

Example:

```bash
docker run \
--tty \
--interactive \
--user root \
--env ASCLI_HOME=/home/cliuser/.aspera/ascli \
--volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli \
martinlaurent/ascli:4.10.0 \
ascli conf over
```

This way, `ascli` is run as root and can write to the host.

**Comment by laurent-martin** [comment]
I have pushed docker image version 4.10.1
note that it has an ENTRYPOINT, so remove `ascli` from command line.

So for example, create an alias (or a script, like `dascli` in repo):

```bash
alias ascli="docker run --rm --tty --interactive --user root --env ASCLI_HOME=/home/cliuser/.aspera/ascli --volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli martinlaurent/ascli:latest"
mkdir -p $HOME/.aspera/ascli
```

And then use normally:

```bash
ascli conf preset over
```

**Comment by mrzool** [comment]
Thanks a lot for patching this so quickly. The container doesn't seem to crash anymore (at least I'm not seeing any error) but I still can't get shell access. The container outputs the `ascli` man page and then exits right away. I'm unable to keep it running and get the shell access that I need.

Any idea why this is happening?

Command tested:

`sudo docker run --rm --tty --user root --env ASCLI_HOME=/home/cliuser/.aspera/ascli --volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli martinlaurent/ascli:latest`

**Comment by laurent-martin** [comment]
Yes, that is intentional, the default command is "-h"

So, just add your commands as argument such as:

```

docker run --rm --tty --user root --env ASCLI_HOME=/home/cliuser/.aspera/ascli --volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli martinlaurent/ascli:latest conf preset over
```

**Comment by mrzool** [comment]
Thanks for clarifying. Now I understand why you suggested to alias `docker run` to `ascli`.

It would be great if I could keep the container running and get shell access though, because I don't know `ascli` at all and I'd like to experiment with it and read the help at leisure.

Any way to achieve that?

**Comment by laurent-martin** [comment]
Current version of ascli is designed to execute a single command per invocation (process).
Currently, is does not provide the possibility to be used as a shell, as shell capabilities (loops, variables, etc...) are best implemented by a shell (bash, zsh, etc..)

If you want to execute multiple ascli commands in a shell you can do the following:

```
docker run --rm --name asclishell --tty --interactive --user root --env ASCLI_HOME=/home/cliuser/.aspera/ascli --volume $HOME/.aspera/ascli:/home/cliuser/.aspera/ascli --entrypoint bash martinlaurent/ascli:latest
```

> Note the `--entrypoint bash` which tells to execute a shell instead of `ascli`

**Comment by laurent-martin** [comment]
Doc has been updated.
